# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1 import example_pb2 as v1_dot_example__pb2


class CurrencyRateStub(object):
  """Работа с курсами валют
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListCbrRates = channel.unary_unary(
        '/devision.example.v1.CurrencyRate/ListCbrRates',
        request_serializer=v1_dot_example__pb2.ListCbrRatesRequest.SerializeToString,
        response_deserializer=v1_dot_example__pb2.ListCbrRatesResponse.FromString,
        )


class CurrencyRateServicer(object):
  """Работа с курсами валют
  """

  def ListCbrRates(self, request, context):
    """Получение курса валют к рублю от Центробанка
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CurrencyRateServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListCbrRates': grpc.unary_unary_rpc_method_handler(
          servicer.ListCbrRates,
          request_deserializer=v1_dot_example__pb2.ListCbrRatesRequest.FromString,
          response_serializer=v1_dot_example__pb2.ListCbrRatesResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'devision.example.v1.CurrencyRate', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class UserStub(object):
  """Работа с текущим пользователям
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMe = channel.unary_unary(
        '/devision.example.v1.User/GetMe',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=v1_dot_example__pb2.GetMeResponse.FromString,
        )


class UserServicer(object):
  """Работа с текущим пользователям
  """

  def GetMe(self, request, context):
    """Получение информации по пользователю, вызывающему API
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMe': grpc.unary_unary_rpc_method_handler(
          servicer.GetMe,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=v1_dot_example__pb2.GetMeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'devision.example.v1.User', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
